var searchData=
[
  ['c_5f',['C_',['../classCCC_1_1StateSpaceModel.html#aeae9c5ee147c753fcf6b28bf12c67085',1,'CCC::StateSpaceModel']]],
  ['calcdiscmatrix',['calcDiscMatrix',['../classCCC_1_1StateSpaceModel.html#a7e1064166faa7edbab396a66ccc79564',1,'CCC::StateSpaceModel']]],
  ['calcgain',['calcGain',['../classCCC_1_1PreviewControl.html#a6fb0138bf23d4daef5a57fb9e2e66c6c',1,'CCC::PreviewControl']]],
  ['calcoptimalinput',['calcOptimalInput',['../classCCC_1_1PreviewControl.html#aca003780b5f9b7f2b44cc47a217355ef',1,'CCC::PreviewControl']]],
  ['calcrunningcostderiv',['calcRunningCostDeriv',['../classCCC_1_1DdpZmp_1_1DdpProblem.html#a206eb6672d8d0bd6b68d4f5036008d2f',1,'CCC::DdpZmp::DdpProblem::calcRunningCostDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateDimVector &gt; running_cost_deriv_x, Eigen::Ref&lt; InputDimVector &gt; running_cost_deriv_u) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#a30685c32c9853c09c0561383de03ba24',1,'CCC::DdpZmp::DdpProblem::calcRunningCostDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateDimVector &gt; running_cost_deriv_x, Eigen::Ref&lt; InputDimVector &gt; running_cost_deriv_u, Eigen::Ref&lt; StateStateDimMatrix &gt; running_cost_deriv_xx, Eigen::Ref&lt; InputInputDimMatrix &gt; running_cost_deriv_uu, Eigen::Ref&lt; StateInputDimMatrix &gt; running_cost_deriv_xu) const override']]],
  ['calcstateeqderiv',['calcStateEqDeriv',['../classCCC_1_1DdpZmp_1_1DdpProblem.html#aa41bf0f198f29a99c314aa0fb101acfc',1,'CCC::DdpZmp::DdpProblem::calcStateEqDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateStateDimMatrix &gt; state_eq_deriv_x, Eigen::Ref&lt; StateInputDimMatrix &gt; state_eq_deriv_u) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#a3985b6b77f9997c79dad57fb82f1af08',1,'CCC::DdpZmp::DdpProblem::calcStateEqDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateStateDimMatrix &gt; state_eq_deriv_x, Eigen::Ref&lt; StateInputDimMatrix &gt; state_eq_deriv_u, std::vector&lt; StateStateDimMatrix &gt; &amp;state_eq_deriv_xx, std::vector&lt; InputInputDimMatrix &gt; &amp;state_eq_deriv_uu, std::vector&lt; StateInputDimMatrix &gt; &amp;state_eq_deriv_xu) const override']]],
  ['calcterminalcostderiv',['calcTerminalCostDeriv',['../classCCC_1_1DdpZmp_1_1DdpProblem.html#a5912c17c8b54b1bd9ac9fab88bb2a228',1,'CCC::DdpZmp::DdpProblem::calcTerminalCostDeriv(double t, const StateDimVector &amp;x, Eigen::Ref&lt; StateDimVector &gt; terminal_cost_deriv_x) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#aea40eac30d7a5c37718185630072cb61',1,'CCC::DdpZmp::DdpProblem::calcTerminalCostDeriv(double t, const StateDimVector &amp;x, Eigen::Ref&lt; StateDimVector &gt; terminal_cost_deriv_x, Eigen::Ref&lt; StateStateDimMatrix &gt; terminal_cost_deriv_xx) const override']]],
  ['ccc',['CCC',['../namespaceCCC.html',1,'']]],
  ['com_5fjerk',['com_jerk',['../structCCC_1_1PreviewControlZmp_1_1WeightParam.html#a252aa1c10d66be0ec88b7b0ce3d51bf4',1,'CCC::PreviewControlZmp::WeightParam']]],
  ['com_5fz',['com_z',['../structCCC_1_1DdpZmp_1_1RefData.html#a898dc4279152c649a8e91360ca144baa',1,'CCC::DdpZmp::RefData::com_z()'],['../structCCC_1_1LinearMpcXY_1_1MotionParam.html#adc8fa47723dd81a795f567dbf25ebc70',1,'CCC::LinearMpcXY::MotionParam::com_z()']]],
  ['commonmodels_2eh',['CommonModels.h',['../CommonModels_8h.html',1,'']]],
  ['comzmpmodeljerkinput',['ComZmpModelJerkInput',['../classCCC_1_1ComZmpModelJerkInput.html',1,'CCC::ComZmpModelJerkInput'],['../classCCC_1_1ComZmpModelJerkInput.html#a1065720d8ecb366e66714739e04ac292',1,'CCC::ComZmpModelJerkInput::ComZmpModelJerkInput()']]],
  ['constants',['constants',['../namespaceCCC_1_1constants.html',1,'CCC']]],
  ['constants_2eh',['Constants.h',['../Constants_8h.html',1,'']]],
  ['contact',['contact',['../structCCC_1_1LinearMpcZ_1_1MotionData.html#a931ea735faadd354dd0e3f09bf57b5a2',1,'CCC::LinearMpcZ::MotionData']]],
  ['current_5fzmp',['current_zmp',['../structCCC_1_1DcmTracking_1_1RefData.html#a1bac9e05508defbed237e58b34da2cf2',1,'CCC::DcmTracking::RefData']]],
  ['centroidal_5fcontrol_5fcollection',['centroidal_control_collection',['../index.html',1,'']]]
];
