var searchData=
[
  ['calcdiscmatrix_248',['calcDiscMatrix',['../classCCC_1_1StateSpaceModel.html#a7e1064166faa7edbab396a66ccc79564',1,'CCC::StateSpaceModel']]],
  ['calcgain_249',['calcGain',['../classCCC_1_1PreviewControl.html#a6fb0138bf23d4daef5a57fb9e2e66c6c',1,'CCC::PreviewControl']]],
  ['calcoptimalinput_250',['calcOptimalInput',['../classCCC_1_1PreviewControl.html#aca003780b5f9b7f2b44cc47a217355ef',1,'CCC::PreviewControl']]],
  ['calcrunningcostderiv_251',['calcRunningCostDeriv',['../classCCC_1_1DdpCentroidal_1_1DdpProblem.html#ab91194a4c78ae89622d10d3421b1cc99',1,'CCC::DdpCentroidal::DdpProblem::calcRunningCostDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateDimVector &gt; running_cost_deriv_x, Eigen::Ref&lt; InputDimVector &gt; running_cost_deriv_u) const override'],['../classCCC_1_1DdpCentroidal_1_1DdpProblem.html#aaf3d400031d6bbd6c52bcb53d895dcd6',1,'CCC::DdpCentroidal::DdpProblem::calcRunningCostDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateDimVector &gt; running_cost_deriv_x, Eigen::Ref&lt; InputDimVector &gt; running_cost_deriv_u, Eigen::Ref&lt; StateStateDimMatrix &gt; running_cost_deriv_xx, Eigen::Ref&lt; InputInputDimMatrix &gt; running_cost_deriv_uu, Eigen::Ref&lt; StateInputDimMatrix &gt; running_cost_deriv_xu) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#a206eb6672d8d0bd6b68d4f5036008d2f',1,'CCC::DdpZmp::DdpProblem::calcRunningCostDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateDimVector &gt; running_cost_deriv_x, Eigen::Ref&lt; InputDimVector &gt; running_cost_deriv_u) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#a30685c32c9853c09c0561383de03ba24',1,'CCC::DdpZmp::DdpProblem::calcRunningCostDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateDimVector &gt; running_cost_deriv_x, Eigen::Ref&lt; InputDimVector &gt; running_cost_deriv_u, Eigen::Ref&lt; StateStateDimMatrix &gt; running_cost_deriv_xx, Eigen::Ref&lt; InputInputDimMatrix &gt; running_cost_deriv_uu, Eigen::Ref&lt; StateInputDimMatrix &gt; running_cost_deriv_xu) const override']]],
  ['calcstateeqderiv_252',['calcStateEqDeriv',['../classCCC_1_1DdpCentroidal_1_1DdpProblem.html#a42771cb9a802c653e6c56300b8cb6d9f',1,'CCC::DdpCentroidal::DdpProblem::calcStateEqDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateStateDimMatrix &gt; state_eq_deriv_x, Eigen::Ref&lt; StateInputDimMatrix &gt; state_eq_deriv_u) const override'],['../classCCC_1_1DdpCentroidal_1_1DdpProblem.html#aa86b018f76ebae8d8df805335fe0b20d',1,'CCC::DdpCentroidal::DdpProblem::calcStateEqDeriv(double, const StateDimVector &amp;, const InputDimVector &amp;, Eigen::Ref&lt; StateStateDimMatrix &gt;, Eigen::Ref&lt; StateInputDimMatrix &gt;, std::vector&lt; StateStateDimMatrix &gt; &amp;, std::vector&lt; InputInputDimMatrix &gt; &amp;, std::vector&lt; StateInputDimMatrix &gt; &amp;) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#aa41bf0f198f29a99c314aa0fb101acfc',1,'CCC::DdpZmp::DdpProblem::calcStateEqDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateStateDimMatrix &gt; state_eq_deriv_x, Eigen::Ref&lt; StateInputDimMatrix &gt; state_eq_deriv_u) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#a8203d07224a25a3c5ed5cd24a30a279f',1,'CCC::DdpZmp::DdpProblem::calcStateEqDeriv(double, const StateDimVector &amp;, const InputDimVector &amp;, Eigen::Ref&lt; StateStateDimMatrix &gt;, Eigen::Ref&lt; StateInputDimMatrix &gt;, std::vector&lt; StateStateDimMatrix &gt; &amp;, std::vector&lt; InputInputDimMatrix &gt; &amp;, std::vector&lt; StateInputDimMatrix &gt; &amp;) const override']]],
  ['calcterminalcostderiv_253',['calcTerminalCostDeriv',['../classCCC_1_1DdpCentroidal_1_1DdpProblem.html#a14a3c93d79ed3ff82412d5614838c88c',1,'CCC::DdpCentroidal::DdpProblem::calcTerminalCostDeriv(double t, const StateDimVector &amp;x, Eigen::Ref&lt; StateDimVector &gt; terminal_cost_deriv_x) const override'],['../classCCC_1_1DdpCentroidal_1_1DdpProblem.html#a51325489a090a74aded19909d9b5662a',1,'CCC::DdpCentroidal::DdpProblem::calcTerminalCostDeriv(double t, const StateDimVector &amp;x, Eigen::Ref&lt; StateDimVector &gt; terminal_cost_deriv_x, Eigen::Ref&lt; StateStateDimMatrix &gt; terminal_cost_deriv_xx) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#a5912c17c8b54b1bd9ac9fab88bb2a228',1,'CCC::DdpZmp::DdpProblem::calcTerminalCostDeriv(double t, const StateDimVector &amp;x, Eigen::Ref&lt; StateDimVector &gt; terminal_cost_deriv_x) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#aea40eac30d7a5c37718185630072cb61',1,'CCC::DdpZmp::DdpProblem::calcTerminalCostDeriv(double t, const StateDimVector &amp;x, Eigen::Ref&lt; StateDimVector &gt; terminal_cost_deriv_x, Eigen::Ref&lt; StateStateDimMatrix &gt; terminal_cost_deriv_xx) const override']]],
  ['centroidalmodel1d_254',['CentroidalModel1d',['../classCCC_1_1PreviewControlCentroidal1d_1_1CentroidalModel1d.html#a7f825e78cc566c20b70a8d5bda1d0e71',1,'CCC::PreviewControlCentroidal1d::CentroidalModel1d']]],
  ['comzmpmodeljerkinput_255',['ComZmpModelJerkInput',['../classCCC_1_1ComZmpModelJerkInput.html#a1065720d8ecb366e66714739e04ac292',1,'CCC::ComZmpModelJerkInput']]]
];
